Handle cases where there is a credential problem, and add upper limit for retries

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -10,6 +10,11 @@ if [[ ${BUILDKITE_COMMAND_EXIT_STATUS:-0} != '0' ]]; then
   exit 0
 fi
 
+if ! aws sts get-caller-identity; then
+  echo "Unable to invalidate cloudfront cache: credentials missing"
+  exit 1
+fi
+
 distribution_id="$(plugin_read_config DISTRIBUTION_ID)"
 paths=()
 while read -r line ; do
@@ -18,9 +23,15 @@ done <<< "$(plugin_read_list PATHS)"
 
 echo "~~~ :cloudfront: Creating Cloudfront invalidation for distribution $distribution_id on paths" "${paths[@]}"
 SLEEP_PERIOD=15
+PERIOD_LIMIT=480
 until aws cloudfront create-invalidation --distribution-id "$distribution_id" --paths "${paths[@]}" --query Invalidation.Id --output text
 do
+  if [ $SLEEP_PERIOD == $PERIOD_LIMIT ]; then
+    echo "Maximum retries reached - giving up..."
+    exit 1
+  fi
   echo "Invalidation failed - retrying in ${SLEEP_PERIOD}"
   sleep ${SLEEP_PERIOD}
   SLEEP_PERIOD=$((SLEEP_PERIOD+SLEEP_PERIOD))
+
 done
