Improve create-invalidation permission check

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -10,12 +10,19 @@ if [[ ${BUILDKITE_COMMAND_EXIT_STATUS:-0} != '0' ]]; then
   exit 0
 fi
 
-if ! aws sts get-caller-identity; then
-  echo "Unable to invalidate cloudfront cache: credentials missing"
+distribution_id="$(plugin_read_config DISTRIBUTION_ID)"
+
+# This tries to create an invalidation with an empty path list
+#
+# - If we have permission to call create-invalidation for this distribution,
+#   we'll recieve an InvalidArgument error, and we can procede with a real invalidation
+# - Otherwise, either an AccessDenied or NoSuchDistribution error are the most likely results,
+#   in which case we exit with error
+if ! aws cloudfront create-invalidation --distribution-id "$distribution_id" --invalidation-batch 'Paths={Quantity=0,Items=[]},CallerReference=cloudfront-invalidation-buildkite-plugin' 2>&1 | grep InvalidArgument > /dev/null; then
+  echo "Unable to invalidate cloudfront cache: create-invalidation not possible for distribution ($distribution_id) with current credentials"
   exit 1
 fi
 
-distribution_id="$(plugin_read_config DISTRIBUTION_ID)"
 paths=()
 while read -r line ; do
   [[ -n "$line" ]] && paths+=("$line")
@@ -33,5 +40,4 @@ do
   echo "Invalidation failed - retrying in ${SLEEP_PERIOD}"
   sleep ${SLEEP_PERIOD}
   SLEEP_PERIOD=$((SLEEP_PERIOD+SLEEP_PERIOD))
-
 done
